const fmt=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1});let DATA=[],charts={};const C={accent:'#ff5a36',muted:'#8e9aa5',grid:'#263039',green:'#75d6a2'};
const sum=(a,f)=>a.reduce((s,x)=>s+(+f(x)||0),0);const dur=s=>{let h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}h ${String(m).padStart(2,'0')}`:`${m} min`};const pace=a=>a.distance_km>0&&a.sport==='Course à pied'?`${Math.floor(a.duration_s/60/a.distance_km)}:${String(Math.round((a.duration_s/60/a.distance_km%1)*60)).padStart(2,'0')}/km`:'—';
function chart(id,type,labels,datasets){if(charts[id])charts[id].destroy();charts[id]=new Chart(document.getElementById(id),{type,data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:C.muted,boxWidth:10}}},scales:type==='doughnut'?{}:{x:{ticks:{color:C.muted},grid:{display:false}},y:{ticks:{color:C.muted},grid:{color:C.grid},beginAtZero:true}}}})}
function render(){const y=document.getElementById('yearFilter').value;let d=y==='all'?DATA:DATA.filter(x=>new Date(x.date).getFullYear()==y);const runs=d.filter(x=>x.sport==='Course à pied');const km=sum(runs,x=>x.distance_km),secs=sum(runs,x=>x.duration_s),elev=sum(runs,x=>x.elevation_m);const weeks=new Set(runs.map(x=>{let z=new Date(x.date),jan=new Date(z.getFullYear(),0,1);return `${z.getFullYear()}-${Math.ceil((((z-jan)/86400000)+jan.getDay()+1)/7)}`}));document.getElementById('kpis').innerHTML=[['Distance',`${fmt.format(km)} km`],['Séances',runs.length],['Temps',dur(secs)],['Dénivelé',`${fmt.format(elev)} m`],['Moy. / sortie',`${fmt.format(runs.length?km/runs.length:0)} km`],['Moy. / sem.',`${fmt.format(weeks.size?km/weeks.size:0)} km`]].map(([l,v])=>`<div class="kpi"><div class="v">${v}</div><div class="l">${l}</div></div>`).join('');
let months=Array(12).fill(0);runs.forEach(x=>months[new Date(x.date).getMonth()]+=x.distance_km);chart('monthlyChart','bar',['Jan','Fév','Mar','Avr','Mai','Juin','Juil','Aoû','Sep','Oct','Nov','Déc'],[{label:'Course à pied',data:months,backgroundColor:C.accent,borderRadius:4}]);
let sports={};d.forEach(x=>sports[x.sport]=(sports[x.sport]||0)+x.duration_s/3600);chart('sportChart','doughnut',Object.keys(sports),[{data:Object.values(sports),backgroundColor:['#ff5a36','#75d6a2','#68a7ff','#f3c969','#a98bff'],borderWidth:0}]);
let years=[...new Set(DATA.map(x=>new Date(x.date).getFullYear()))].sort();let annual=years.map(Y=>sum(DATA.filter(x=>x.sport==='Course à pied'&&new Date(x.date).getFullYear()===Y),x=>x.distance_km));chart('annualChart','line',years,[{label:'km course',data:annual,borderColor:C.accent,backgroundColor:C.accent,tension:.25,pointRadius:4}]);let ae=years.map(Y=>sum(DATA.filter(x=>x.sport==='Course à pied'&&new Date(x.date).getFullYear()===Y),x=>x.elevation_m));chart('elevChart','bar',years,[{label:'D+ course',data:ae,backgroundColor:C.green,borderRadius:4}]);let as=years.map(Y=>DATA.filter(x=>x.sport==='Course à pied'&&new Date(x.date).getFullYear()===Y).length);chart('sessionsChart','bar',years,[{label:'séances course',data:as,backgroundColor:'#68a7ff',borderRadius:4}]);
let now=new Date(Math.max(...DATA.map(x=>new Date(x.date))));let wlabels=[],wdata=[];for(let i=11;i>=0;i--){let end=new Date(now);end.setDate(end.getDate()-7*i);let start=new Date(end);start.setDate(start.getDate()-6);wlabels.push(`${start.getDate()}/${start.getMonth()+1}`);wdata.push(sum(runs.filter(x=>{let z=new Date(x.date);return z>=start&&z<=end}),x=>x.distance_km))}chart('weeklyChart','line',wlabels,[{label:'km / semaine',data:wdata,borderColor:C.green,backgroundColor:C.green,tension:.25}]);
let recent=[...d].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20);document.getElementById('activityCount').textContent=`${d.length} activités`;document.getElementById('activitiesTable').innerHTML=recent.map(a=>`<tr><td>${new Date(a.date).toLocaleDateString('fr-FR')}</td><td><span class="pill">${a.sport}</span></td><td>${fmt.format(a.distance_km)} km</td><td>${dur(a.duration_s)}</td><td>${fmt.format(a.elevation_m)} m</td><td>${pace(a)}</td></tr>`).join('')}
fetch('data/activities.json').then(r=>r.json()).then(d=>{DATA=d;const years=[...new Set(d.map(x=>new Date(x.date).getFullYear()))].sort((a,b)=>b-a);const s=document.getElementById('yearFilter');s.innerHTML='<option value="all">Toutes</option>'+years.map(y=>`<option value="${y}" ${y===years[0]?'selected':''}>${y}</option>`).join('');s.onchange=render;render()}).catch(e=>document.querySelector('main').innerHTML='<div class="card"><h2>Impossible de charger les données</h2><p>Lancez le site via GitHub Pages ou un serveur HTTP local.</p></div>');