name = "luteo-strava-api"
main = "src/index.js"
compatibility_date = "2026-09-29"

[[kv_namespaces]]
binding = "TOKENS"
id = "cebf207103074536a37532f867033588"

[vars]
FRONTEND_URL = "https://luteo14.github.io"
STRAVA_CLIENT_ID = "212577"
